package com.jero.esc.po.map;

import java.util.Date;

public class WxAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.WX_ADMIN_ID
     *
     * @mbggenerated
     */
    private String wxAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.WX_ADMIN_OPENID
     *
     * @mbggenerated
     */
    private String wxAdminOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.WX_ADMIN_TOKEN
     *
     * @mbggenerated
     */
    private String wxAdminToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.WX_ADMIN_R_TOKEN
     *
     * @mbggenerated
     */
    private String wxAdminRToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.WX_ADMIN_CREATETIM
     *
     * @mbggenerated
     */
    private Date wxAdminCreatetim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.WX_ADMIN_UPDATETIME
     *
     * @mbggenerated
     */
    private Date wxAdminUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.WX_ADMIN_LOG
     *
     * @mbggenerated
     */
    private String wxAdminLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_admin.WX_ADMIN_TIMEOUT
     *
     * @mbggenerated
     */
    private Integer wxAdminTimeout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.WX_ADMIN_ID
     *
     * @return the value of wx_admin.WX_ADMIN_ID
     *
     * @mbggenerated
     */
    public String getWxAdminId() {
        return wxAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.WX_ADMIN_ID
     *
     * @param wxAdminId the value for wx_admin.WX_ADMIN_ID
     *
     * @mbggenerated
     */
    public void setWxAdminId(String wxAdminId) {
        this.wxAdminId = wxAdminId == null ? null : wxAdminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.WX_ADMIN_OPENID
     *
     * @return the value of wx_admin.WX_ADMIN_OPENID
     *
     * @mbggenerated
     */
    public String getWxAdminOpenid() {
        return wxAdminOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.WX_ADMIN_OPENID
     *
     * @param wxAdminOpenid the value for wx_admin.WX_ADMIN_OPENID
     *
     * @mbggenerated
     */
    public void setWxAdminOpenid(String wxAdminOpenid) {
        this.wxAdminOpenid = wxAdminOpenid == null ? null : wxAdminOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.WX_ADMIN_TOKEN
     *
     * @return the value of wx_admin.WX_ADMIN_TOKEN
     *
     * @mbggenerated
     */
    public String getWxAdminToken() {
        return wxAdminToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.WX_ADMIN_TOKEN
     *
     * @param wxAdminToken the value for wx_admin.WX_ADMIN_TOKEN
     *
     * @mbggenerated
     */
    public void setWxAdminToken(String wxAdminToken) {
        this.wxAdminToken = wxAdminToken == null ? null : wxAdminToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.WX_ADMIN_R_TOKEN
     *
     * @return the value of wx_admin.WX_ADMIN_R_TOKEN
     *
     * @mbggenerated
     */
    public String getWxAdminRToken() {
        return wxAdminRToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.WX_ADMIN_R_TOKEN
     *
     * @param wxAdminRToken the value for wx_admin.WX_ADMIN_R_TOKEN
     *
     * @mbggenerated
     */
    public void setWxAdminRToken(String wxAdminRToken) {
        this.wxAdminRToken = wxAdminRToken == null ? null : wxAdminRToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.WX_ADMIN_CREATETIM
     *
     * @return the value of wx_admin.WX_ADMIN_CREATETIM
     *
     * @mbggenerated
     */
    public Date getWxAdminCreatetim() {
        return wxAdminCreatetim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.WX_ADMIN_CREATETIM
     *
     * @param wxAdminCreatetim the value for wx_admin.WX_ADMIN_CREATETIM
     *
     * @mbggenerated
     */
    public void setWxAdminCreatetim(Date wxAdminCreatetim) {
        this.wxAdminCreatetim = wxAdminCreatetim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.WX_ADMIN_UPDATETIME
     *
     * @return the value of wx_admin.WX_ADMIN_UPDATETIME
     *
     * @mbggenerated
     */
    public Date getWxAdminUpdatetime() {
        return wxAdminUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.WX_ADMIN_UPDATETIME
     *
     * @param wxAdminUpdatetime the value for wx_admin.WX_ADMIN_UPDATETIME
     *
     * @mbggenerated
     */
    public void setWxAdminUpdatetime(Date wxAdminUpdatetime) {
        this.wxAdminUpdatetime = wxAdminUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.WX_ADMIN_LOG
     *
     * @return the value of wx_admin.WX_ADMIN_LOG
     *
     * @mbggenerated
     */
    public String getWxAdminLog() {
        return wxAdminLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.WX_ADMIN_LOG
     *
     * @param wxAdminLog the value for wx_admin.WX_ADMIN_LOG
     *
     * @mbggenerated
     */
    public void setWxAdminLog(String wxAdminLog) {
        this.wxAdminLog = wxAdminLog == null ? null : wxAdminLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_admin.WX_ADMIN_TIMEOUT
     *
     * @return the value of wx_admin.WX_ADMIN_TIMEOUT
     *
     * @mbggenerated
     */
    public Integer getWxAdminTimeout() {
        return wxAdminTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_admin.WX_ADMIN_TIMEOUT
     *
     * @param wxAdminTimeout the value for wx_admin.WX_ADMIN_TIMEOUT
     *
     * @mbggenerated
     */
    public void setWxAdminTimeout(Integer wxAdminTimeout) {
        this.wxAdminTimeout = wxAdminTimeout;
    }
}