package com.jero.esc.po.shiro;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

public class Apptoken {


    private Map<String,Object> map=new HashMap<String, Object>();


    public Map<String, Object> getMap() {
        return map;
    }

    public void setMap(Map<String, Object> map) {
        this.map = map;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptoken.apptoken_id
     *
     * @mbggenerated
     */
    private String apptokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptoken.apptoken_token
     *
     * @mbggenerated
     */
    private String apptokenToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptoken.apptoken_starttime
     *
     * @mbggenerated
     */
    private Date apptokenStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptoken.apptoken_endtime
     *
     * @mbggenerated
     */
    private Date apptokenEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptoken.apptoken_log
     *
     * @mbggenerated
     */
    private String apptokenLog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptoken.apptoken_id
     *
     * @return the value of apptoken.apptoken_id
     *
     * @mbggenerated
     */
    public String getApptokenId() {
        return apptokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptoken.apptoken_id
     *
     * @param apptokenId the value for apptoken.apptoken_id
     *
     * @mbggenerated
     */
    public void setApptokenId(String apptokenId) {
        this.apptokenId = apptokenId == null ? null : apptokenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptoken.apptoken_token
     *
     * @return the value of apptoken.apptoken_token
     *
     * @mbggenerated
     */
    public String getApptokenToken() {
        return apptokenToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptoken.apptoken_token
     *
     * @param apptokenToken the value for apptoken.apptoken_token
     *
     * @mbggenerated
     */
    public void setApptokenToken(String apptokenToken) {
        this.apptokenToken = apptokenToken == null ? null : apptokenToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptoken.apptoken_starttime
     *
     * @return the value of apptoken.apptoken_starttime
     *
     * @mbggenerated
     */
    public Date getApptokenStarttime() {
        return apptokenStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptoken.apptoken_starttime
     *
     * @param apptokenStarttime the value for apptoken.apptoken_starttime
     *
     * @mbggenerated
     */
    public void setApptokenStarttime(Date apptokenStarttime) {
        this.apptokenStarttime = apptokenStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptoken.apptoken_endtime
     *
     * @return the value of apptoken.apptoken_endtime
     *
     * @mbggenerated
     */
    public Date getApptokenEndtime() {
        return apptokenEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptoken.apptoken_endtime
     *
     * @param apptokenEndtime the value for apptoken.apptoken_endtime
     *
     * @mbggenerated
     */
    public void setApptokenEndtime(Date apptokenEndtime) {
        this.apptokenEndtime = apptokenEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptoken.apptoken_log
     *
     * @return the value of apptoken.apptoken_log
     *
     * @mbggenerated
     */
    public String getApptokenLog() {
        return apptokenLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptoken.apptoken_log
     *
     * @param apptokenLog the value for apptoken.apptoken_log
     *
     * @mbggenerated
     */
    public void setApptokenLog(String apptokenLog) {
        this.apptokenLog = apptokenLog == null ? null : apptokenLog.trim();
    }
}