package com.jero.esc.mapper.shiro;

import com.jero.esc.po.shiro.Apptoken;
import com.jero.esc.po.shiro.ApptokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApptokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int countByExample(ApptokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int deleteByExample(ApptokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String apptokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int insert(Apptoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int insertSelective(Apptoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    List<Apptoken> selectByExample(ApptokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    Apptoken selectByPrimaryKey(String apptokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Apptoken record, @Param("example") ApptokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Apptoken record, @Param("example") ApptokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Apptoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Apptoken record);
}