package com.jero.esc.po.map;

import org.apache.commons.lang3.builder.ToStringBuilder;

import com.alibaba.fastjson.JSON;

public class Point {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.POINT_ID
     *
     * @mbggenerated
     */
    private String pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.POINT_LBS_ID
     *
     * @mbggenerated
     */
    private String pointLbsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.POINT_PROVIDER
     *
     * @mbggenerated
     */
    private String pointProvider;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.POINT_LAT
     *
     * @mbggenerated
     */
    private Float pointLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.POINT_LNG
     *
     * @mbggenerated
     */
    private Float pointLng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.POINT_ID
     *
     * @return the value of point.POINT_ID
     *
     * @mbggenerated
     */
    public String getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.POINT_ID
     *
     * @param pointId the value for point.POINT_ID
     *
     * @mbggenerated
     */
    public void setPointId(String pointId) {
        this.pointId = pointId == null ? null : pointId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.POINT_LBS_ID
     *
     * @return the value of point.POINT_LBS_ID
     *
     * @mbggenerated
     */
    public String getPointLbsId() {
        return pointLbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.POINT_LBS_ID
     *
     * @param pointLbsId the value for point.POINT_LBS_ID
     *
     * @mbggenerated
     */
    public void setPointLbsId(String pointLbsId) {
        this.pointLbsId = pointLbsId == null ? null : pointLbsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.POINT_PROVIDER
     *
     * @return the value of point.POINT_PROVIDER
     *
     * @mbggenerated
     */
    public String getPointProvider() {
        return pointProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.POINT_PROVIDER
     *
     * @param pointProvider the value for point.POINT_PROVIDER
     *
     * @mbggenerated
     */
    public void setPointProvider(String pointProvider) {
        this.pointProvider = pointProvider == null ? null : pointProvider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.POINT_LAT
     *
     * @return the value of point.POINT_LAT
     *
     * @mbggenerated
     */
    public Float getPointLat() {
        return pointLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.POINT_LAT
     *
     * @param pointLat the value for point.POINT_LAT
     *
     * @mbggenerated
     */
    public void setPointLat(Float pointLat) {
        this.pointLat = pointLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.POINT_LNG
     *
     * @return the value of point.POINT_LNG
     *
     * @mbggenerated
     */
    public Float getPointLng() {
        return pointLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.POINT_LNG
     *
     * @param pointLng the value for point.POINT_LNG
     *
     * @mbggenerated
     */
    public void setPointLng(Float pointLng) {
        this.pointLng = pointLng;
    }
    
    public String toString(){
    	return JSON.toJSONString(this);
    }
}