package com.jero.esc.po.pubinfo;

public class CommonTypeSave {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_type_save.SAVE_ID
     *
     * @mbggenerated
     */
    private String saveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_type_save.SAVE_TYPE
     *
     * @mbggenerated
     */
    private String saveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_type_save.SAVE_TYPE_NAME
     *
     * @mbggenerated
     */
    private String saveTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_type_save.SAVE_VALUE
     *
     * @mbggenerated
     */
    private String saveValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_type_save.SAVE_ID
     *
     * @return the value of common_type_save.SAVE_ID
     *
     * @mbggenerated
     */
    public String getSaveId() {
        return saveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_type_save.SAVE_ID
     *
     * @param saveId the value for common_type_save.SAVE_ID
     *
     * @mbggenerated
     */
    public void setSaveId(String saveId) {
        this.saveId = saveId == null ? null : saveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_type_save.SAVE_TYPE
     *
     * @return the value of common_type_save.SAVE_TYPE
     *
     * @mbggenerated
     */
    public String getSaveType() {
        return saveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_type_save.SAVE_TYPE
     *
     * @param saveType the value for common_type_save.SAVE_TYPE
     *
     * @mbggenerated
     */
    public void setSaveType(String saveType) {
        this.saveType = saveType == null ? null : saveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_type_save.SAVE_TYPE_NAME
     *
     * @return the value of common_type_save.SAVE_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getSaveTypeName() {
        return saveTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_type_save.SAVE_TYPE_NAME
     *
     * @param saveTypeName the value for common_type_save.SAVE_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setSaveTypeName(String saveTypeName) {
        this.saveTypeName = saveTypeName == null ? null : saveTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_type_save.SAVE_VALUE
     *
     * @return the value of common_type_save.SAVE_VALUE
     *
     * @mbggenerated
     */
    public String getSaveValue() {
        return saveValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_type_save.SAVE_VALUE
     *
     * @param saveValue the value for common_type_save.SAVE_VALUE
     *
     * @mbggenerated
     */
    public void setSaveValue(String saveValue) {
        this.saveValue = saveValue == null ? null : saveValue.trim();
    }
    private  String company;
    public String getCompany() {
        return company;
    }
    public void setCompany(String company) {
        this.company = company;
    }
}