package com.jero.esc.po.pubinfo;

import java.util.ArrayList;
import java.util.List;

public class CommonTypeSaveExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public CommonTypeSaveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSaveIdIsNull() {
            addCriterion("SAVE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSaveIdIsNotNull() {
            addCriterion("SAVE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSaveIdEqualTo(String value) {
            addCriterion("SAVE_ID =", value, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdNotEqualTo(String value) {
            addCriterion("SAVE_ID <>", value, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdGreaterThan(String value) {
            addCriterion("SAVE_ID >", value, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdGreaterThanOrEqualTo(String value) {
            addCriterion("SAVE_ID >=", value, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdLessThan(String value) {
            addCriterion("SAVE_ID <", value, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdLessThanOrEqualTo(String value) {
            addCriterion("SAVE_ID <=", value, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdLike(String value) {
            addCriterion("SAVE_ID like", value, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdNotLike(String value) {
            addCriterion("SAVE_ID not like", value, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdIn(List<String> values) {
            addCriterion("SAVE_ID in", values, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdNotIn(List<String> values) {
            addCriterion("SAVE_ID not in", values, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdBetween(String value1, String value2) {
            addCriterion("SAVE_ID between", value1, value2, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveIdNotBetween(String value1, String value2) {
            addCriterion("SAVE_ID not between", value1, value2, "saveId");
            return (Criteria) this;
        }

        public Criteria andSaveTypeIsNull() {
            addCriterion("SAVE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSaveTypeIsNotNull() {
            addCriterion("SAVE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSaveTypeEqualTo(String value) {
            addCriterion("SAVE_TYPE =", value, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNotEqualTo(String value) {
            addCriterion("SAVE_TYPE <>", value, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeGreaterThan(String value) {
            addCriterion("SAVE_TYPE >", value, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SAVE_TYPE >=", value, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeLessThan(String value) {
            addCriterion("SAVE_TYPE <", value, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeLessThanOrEqualTo(String value) {
            addCriterion("SAVE_TYPE <=", value, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeLike(String value) {
            addCriterion("SAVE_TYPE like", value, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNotLike(String value) {
            addCriterion("SAVE_TYPE not like", value, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeIn(List<String> values) {
            addCriterion("SAVE_TYPE in", values, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNotIn(List<String> values) {
            addCriterion("SAVE_TYPE not in", values, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeBetween(String value1, String value2) {
            addCriterion("SAVE_TYPE between", value1, value2, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNotBetween(String value1, String value2) {
            addCriterion("SAVE_TYPE not between", value1, value2, "saveType");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameIsNull() {
            addCriterion("SAVE_TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameIsNotNull() {
            addCriterion("SAVE_TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameEqualTo(String value) {
            addCriterion("SAVE_TYPE_NAME =", value, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameNotEqualTo(String value) {
            addCriterion("SAVE_TYPE_NAME <>", value, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameGreaterThan(String value) {
            addCriterion("SAVE_TYPE_NAME >", value, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("SAVE_TYPE_NAME >=", value, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameLessThan(String value) {
            addCriterion("SAVE_TYPE_NAME <", value, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameLessThanOrEqualTo(String value) {
            addCriterion("SAVE_TYPE_NAME <=", value, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameLike(String value) {
            addCriterion("SAVE_TYPE_NAME like", value, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameNotLike(String value) {
            addCriterion("SAVE_TYPE_NAME not like", value, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameIn(List<String> values) {
            addCriterion("SAVE_TYPE_NAME in", values, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameNotIn(List<String> values) {
            addCriterion("SAVE_TYPE_NAME not in", values, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameBetween(String value1, String value2) {
            addCriterion("SAVE_TYPE_NAME between", value1, value2, "saveTypeName");
            return (Criteria) this;
        }

        public Criteria andSaveTypeNameNotBetween(String value1, String value2) {
            addCriterion("SAVE_TYPE_NAME not between", value1, value2, "saveTypeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table common_type_save
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}