package com.jero.esc.mapper.map;

import com.jero.esc.po.map.Point;
import com.jero.esc.po.map.PointExample;
import java.util.List;

public interface PointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    int insert(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    int insertSelective(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    List<Point> selectByExample(PointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    Point selectByPrimaryKey(String pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    Point selectByLogId(String logId);
    
    
    int updateByPrimaryKeySelective(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Point record);
}