package com.jero.esc.mapper.pubinfo;

import com.jero.esc.po.pubinfo.CommonTypeSave;
import com.jero.esc.po.pubinfo.CommonTypeSaveExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommonTypeSaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String saveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    int insert(CommonTypeSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    int insertSelective(CommonTypeSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    List<CommonTypeSave> selectByExampleWithBLOBs(CommonTypeSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    List<CommonTypeSave> selectByExample(CommonTypeSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    CommonTypeSave selectByPrimaryKey(String saveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommonTypeSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CommonTypeSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_type_save
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommonTypeSave record);

	CommonTypeSave queryServiceTypeSave(@Param("saveType") String saveType,@Param("com") String com);
}