package com.jero.esc.po.shiro;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApptokenExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public ApptokenExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApptokenIdIsNull() {
            addCriterion("apptoken_id is null");
            return (Criteria) this;
        }

        public Criteria andApptokenIdIsNotNull() {
            addCriterion("apptoken_id is not null");
            return (Criteria) this;
        }

        public Criteria andApptokenIdEqualTo(String value) {
            addCriterion("apptoken_id =", value, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdNotEqualTo(String value) {
            addCriterion("apptoken_id <>", value, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdGreaterThan(String value) {
            addCriterion("apptoken_id >", value, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdGreaterThanOrEqualTo(String value) {
            addCriterion("apptoken_id >=", value, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdLessThan(String value) {
            addCriterion("apptoken_id <", value, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdLessThanOrEqualTo(String value) {
            addCriterion("apptoken_id <=", value, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdLike(String value) {
            addCriterion("apptoken_id like", value, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdNotLike(String value) {
            addCriterion("apptoken_id not like", value, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdIn(List<String> values) {
            addCriterion("apptoken_id in", values, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdNotIn(List<String> values) {
            addCriterion("apptoken_id not in", values, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdBetween(String value1, String value2) {
            addCriterion("apptoken_id between", value1, value2, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenIdNotBetween(String value1, String value2) {
            addCriterion("apptoken_id not between", value1, value2, "apptokenId");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenIsNull() {
            addCriterion("apptoken_token is null");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenIsNotNull() {
            addCriterion("apptoken_token is not null");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenEqualTo(String value) {
            addCriterion("apptoken_token =", value, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenNotEqualTo(String value) {
            addCriterion("apptoken_token <>", value, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenGreaterThan(String value) {
            addCriterion("apptoken_token >", value, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenGreaterThanOrEqualTo(String value) {
            addCriterion("apptoken_token >=", value, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenLessThan(String value) {
            addCriterion("apptoken_token <", value, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenLessThanOrEqualTo(String value) {
            addCriterion("apptoken_token <=", value, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenLike(String value) {
            addCriterion("apptoken_token like", value, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenNotLike(String value) {
            addCriterion("apptoken_token not like", value, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenIn(List<String> values) {
            addCriterion("apptoken_token in", values, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenNotIn(List<String> values) {
            addCriterion("apptoken_token not in", values, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenBetween(String value1, String value2) {
            addCriterion("apptoken_token between", value1, value2, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenTokenNotBetween(String value1, String value2) {
            addCriterion("apptoken_token not between", value1, value2, "apptokenToken");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeIsNull() {
            addCriterion("apptoken_starttime is null");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeIsNotNull() {
            addCriterion("apptoken_starttime is not null");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeEqualTo(Date value) {
            addCriterion("apptoken_starttime =", value, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeNotEqualTo(Date value) {
            addCriterion("apptoken_starttime <>", value, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeGreaterThan(Date value) {
            addCriterion("apptoken_starttime >", value, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("apptoken_starttime >=", value, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeLessThan(Date value) {
            addCriterion("apptoken_starttime <", value, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("apptoken_starttime <=", value, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeIn(List<Date> values) {
            addCriterion("apptoken_starttime in", values, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeNotIn(List<Date> values) {
            addCriterion("apptoken_starttime not in", values, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeBetween(Date value1, Date value2) {
            addCriterion("apptoken_starttime between", value1, value2, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("apptoken_starttime not between", value1, value2, "apptokenStarttime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeIsNull() {
            addCriterion("apptoken_endtime is null");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeIsNotNull() {
            addCriterion("apptoken_endtime is not null");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeEqualTo(Date value) {
            addCriterion("apptoken_endtime =", value, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeNotEqualTo(Date value) {
            addCriterion("apptoken_endtime <>", value, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeGreaterThan(Date value) {
            addCriterion("apptoken_endtime >", value, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("apptoken_endtime >=", value, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeLessThan(Date value) {
            addCriterion("apptoken_endtime <", value, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("apptoken_endtime <=", value, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeIn(List<Date> values) {
            addCriterion("apptoken_endtime in", values, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeNotIn(List<Date> values) {
            addCriterion("apptoken_endtime not in", values, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeBetween(Date value1, Date value2) {
            addCriterion("apptoken_endtime between", value1, value2, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("apptoken_endtime not between", value1, value2, "apptokenEndtime");
            return (Criteria) this;
        }

        public Criteria andApptokenLogIsNull() {
            addCriterion("apptoken_log is null");
            return (Criteria) this;
        }

        public Criteria andApptokenLogIsNotNull() {
            addCriterion("apptoken_log is not null");
            return (Criteria) this;
        }

        public Criteria andApptokenLogEqualTo(String value) {
            addCriterion("apptoken_log =", value, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogNotEqualTo(String value) {
            addCriterion("apptoken_log <>", value, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogGreaterThan(String value) {
            addCriterion("apptoken_log >", value, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogGreaterThanOrEqualTo(String value) {
            addCriterion("apptoken_log >=", value, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogLessThan(String value) {
            addCriterion("apptoken_log <", value, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogLessThanOrEqualTo(String value) {
            addCriterion("apptoken_log <=", value, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogLike(String value) {
            addCriterion("apptoken_log like", value, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogNotLike(String value) {
            addCriterion("apptoken_log not like", value, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogIn(List<String> values) {
            addCriterion("apptoken_log in", values, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogNotIn(List<String> values) {
            addCriterion("apptoken_log not in", values, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogBetween(String value1, String value2) {
            addCriterion("apptoken_log between", value1, value2, "apptokenLog");
            return (Criteria) this;
        }

        public Criteria andApptokenLogNotBetween(String value1, String value2) {
            addCriterion("apptoken_log not between", value1, value2, "apptokenLog");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apptoken
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}